### PR TITLE
Enabled `ferium add` to take in multiple mod identifiers

### PR DESCRIPTION
**Pull request by Broyojo**
This patch directly addresses #175. It allows you to add multiple mods at once using the `ferium add` command like so: `ferium add sodium lithium starlight`. I added some tests to test adding multiple mods at once.

### CODE REVIEW

**Comment by theRookieCoder** [comment]
Ok so I have thought about how to implement adding multiple mods before, and sorry but this implementation is not it. Firstly, the check override flags just don't work properly in this method. The main big problem is that ferium's number 1 priority is to make as few network requests as possible, that's the main bottleneck of this program. This implementation is inefficient in that regard as it makes multiple requests for each mod and it's dependencies. I really appreciate your effort though, so thank you!

**Comment by Broyojo** [comment]
Thanks for the feedback, I'll try to do better in the future 👍

**Comment by theRookieCoder** [comment]
No problem! Your implementation was fine, it's just that the way adding mods currently works is a little difficult to manage, and I am planning to overhaul it into a sort of 'wizard' with the multiple mods feature.

**Comment by Neboer** [comment]
This is bad, I think this feature should be a must-have thing. The project is good, but it is also very hard to use. Please consider to add the function, to prove you are REALLY fast.

**Pull request closed without merging**
