### PR TITLE
CLI tweaks resolving #250

### PR DESCRIPTION
**Pull request by T3sT3ro**
Partially implemented #250 

- [x] ~~`ferium info` should show information about the current profile and modpack~~
  - [x] `ferium profile info` added instead to be more scoped 
  - [x] `ferium modpack info` info should be added in a similar manner
- [x] `ferium profile list` - tweaked the active profile indicator to be bold green `(active)` suffix next to profile name.
- [x] When `ferium add` fails, ~~link to documentation about overrides (https://github.com/gorilla-devs/ferium#check-overrides)~~ hint about `--dont-check-*` flags as part of the error message.
- [x] ~~`ferium profile` should print the current profile, then Run `ferium profile -h` for more info about this command (likewise for ferium modpack too)~~ instead use `ferium profile info` to align with current usage patterns
- [x] `ferium list` should print a header with information about the profile about to be listed (i.e. profile name, loader, and mc version) as well
  - [x] added support for `--markdown` flag in the `ferium list -vm` variant
- [x] `ferium profile switch` should print more info about the profiles, not just the names 
  - [x] ~~likewise for `ferium modpack switch`~~ no need for that
- [x] `ferium profiles` should be an alias to `ferium profile list` (likewise for `ferium modpacks` too)
- [x] `ferium mods` should be an alias to `ferium list`
- [x] `ferium remove` should print the project id of the removed mods too

### CODE REVIEW

**Comment by theRookieCoder** [comment]
Hmm I don't think a separate info subcommand is needed, I was thinking something like that would be added to the list command instead.

**Comment by T3sT3ro** [comment]
In the original proposal I mentioned `ferium info`. I noticed, that it's more idiomatic to write `ferium profile info` to get a short info about a profile (modpack, version) that it would be to have a `ferium info` which is hard to explain what should do:
- Should it print both active profile and active modpack info? Why would I need those two things at the same time?
- How would `ferium info` be different than `ferium list`? Is `list` just a superset of `info`?
- If new project types come into ferium in the future, how would someone get a quick info about each type of project - modpack, resourcepack, shaderpack, profile?

I also noticed, that I often switch profiles and need to know the most crucial info about my active one:
- MC version
- loader
- name

If I were to implement the original proposal of including profile info in the `ferium list` without the separate `ferium profile info`, then I would always get more output than I wanted, and couldn't access above information alone:

- `ferium list` would print BOTH profile info and modpack list (possibly long), so i would have to scroll to the top to get what I wanted
- `ferium profile list` is the only other way to display info, but it also includes other profiles which I might not be interested in. Additionally I would have to search for the active profile in this list, which also takes time.

I noticed that I started using `ferium profile info` right away - it gives crucial info in a simplest way.

**Comment by T3sT3ro** [comment]
I don't know how to add an alias `ferium profiles` to `ferium profile list`.

There is still alphabetical printing in verbose listing and corresponding subcommands for `modpack` and tests to write (if any).

**Comment by T3sT3ro** [comment]
I've noticed, that the download log after `ferium update` still has the issue of aligning texts using unicode emojis:
image

I noticed it's a problem with padded rust macros e.g. `format!({:40}, "<unicode emoji>")` where emoji's width is not properly calculated. This is related to https://github.com/rust-lang/rust/issues/30646

**Comment by T3sT3ro** [comment]
I think this can be merged for now as-is after you review @theRookieCoder. If you have some idea how to deal properly with emoji character widths in padded `fmt!` (and similar) macros, you can adjust them accordingly.

I am a bit hesitant to add `profiles` alias to `profile list`, as I imagine it can get later a bit confusing for players, if they for example often use `ferium profiles`. I imagine they may mistakenly type `ferium profiles create ...` and it will be prompting them with errors.

**Comment by T3sT3ro** [comment]
@theRookieCoder, will you merge?

**Comment by T3sT3ro** [comment]
@blarfoon it would be good if you changed cla-bot so it doesn't require sending the email but simply clicking a button/commenting.

**Comment by blarfoon** [comment]
Yeah eventually you'll just need to click a link and sign the document, this email thing is temporary. Sorry for the inconvenience

**Comment by theRookieCoder** [comment]
I'm really sorry @T3sT3ro but I genuinely forgot about this PR when implementing these features. I've implemented most of these features in a36316a68998bb332c92c98553cbfe4296562613

**Comment by T3sT3ro** [comment]
Damn, too bad :P Is there something missing from you commit that was present in the PR?

**Pull request closed without merging**
