### PR TITLE
Add scanning functionality

### PR DESCRIPTION
**Pull request by tuxinal**
same as #170 but squashed to avoid the mess

### CODE REVIEW

**Comment by WillXProject** [comment]
it's a bit weird since it doesn't seem to build properly

**Comment by tippfehlr** [comment]
> it's a bit weird since it doesn't seem to build properly

I can confirm that this isn’t building:

```
error[E0432]: unresolved imports `libium::config::structs::ModPlatform`, `libium::scan`
  --> src/subcommands/scan.rs:9:43
   |
9  |     config::structs::{Mod, ModIdentifier, ModPlatform, Profile},
   |                                           ^^^^^^^^^^^ no `ModPlatform` in `config::structs`
10 |     scan,
   |     ^^^^ no `scan` in the root
   |
   = help: consider importing this module instead:
           crate::subcommands::scan

error[E0433]: failed to resolve: could not find `ModPlatform` in `structs`
   --> src/main.rs:357:71
    |
357 |                 preferred_platform.unwrap_or(libium::config::structs::ModPlatform::Modrinth),
    |                                                                       ^^^^^^^^^^^ could not find `ModPlatform` in `structs`

error[E0412]: cannot find type `ModPlatform` in module `libium::config::structs`
  --> src/cli.rs:90:61
   |
90 |         preferred_platform: Option<libium::config::structs::ModPlatform>
   |                                                             ^^^^^^^^^^^ not found in `libium::config::structs`

error[E0412]: cannot find type `ModPlatform` in module `libium::config::structs`
  --> src/subcommands/scan.rs:18:50
   |
18 |     preferred_platform: libium::config::structs::ModPlatform,
   |                                                  ^^^^^^^^^^^ not found in `libium::config::structs`

error[E0609]: no field `project_id` on type `&_`
  --> src/subcommands/scan.rs:51:69
   |
51 |                         ModIdentifier::ModrinthProject(modrinth_mod.project_id.clone())
   |                                                                     ^^^^^^^^^^

error[E0609]: no field `mod_id` on type `&_`
  --> src/subcommands/scan.rs:54:73
   |
54 |                         ModIdentifier::CurseForgeProject(curseforge_mod.mod_id)
   |                                                                         ^^^^^^

Some errors have detailed explanations: E0412, E0432, E0433, E0609.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `ferium` due to 6 previous errors
```

**Comment by tuxinal** [comment]
you have to change the libium dependency in `Cargo.toml` to [the squash branch of my fork](https://github.com/tuxinal/libium/tree/squash) for it to build 
> What does this do? Scan a folder for importing existing mods into ferium?

Yes exactly that see #57

**Comment by WillXProject** [comment]
why haven't you done that?
and your branch is many commits behind

**Comment by theRookieCoder** [comment]
> why haven't you done that?

Tuxinal is probably waiting for upstream changes that allow multiple mods to be properly added.

Also please change your tone, slow progress is typical of open source projects, and in the majority of cases it is up to the authors to spare their free time for the project. I'd be more than happy if you'd like to help us out, we have tons of requested features in the backlog. They are all publicly tracked in GitHub Issues so that everyone can contribute, even with non-programming related tasks like auditing theoretical enhancements or planning out large structural changes.

**Comment by WillXProject** [comment]
> Also please change your tone
sorry, I was annoyed at the time because of personal issues

**Comment by theRookieCoder** [comment]
Superseded by 9929937b0594f9f562e77631b436a2268742f598

**Pull request closed without merging**
